// @generated by protoc-gen-connect-query v1.4.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/greet/greet.proto (package greet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HelloRequest, HelloResponse } from "./greet_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from rpc greet.Greet.SayHello
 */
export const sayHello: {
      readonly name: "SayHello",
      readonly I: typeof HelloRequest,
      readonly O: typeof HelloResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "greet.Greet"
  }
};
