// @generated by protoc-gen-connect-es v1.4.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/greet/greet.proto (package greet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HelloRequest, HelloResponse } from "./greet_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service greet.Greet
 */
export declare const Greet: {
  readonly typeName: "greet.Greet",
  readonly methods: {
    /**
     * @generated from rpc greet.Greet.SayHello
     */
    readonly sayHello: {
      readonly name: "SayHello",
      readonly I: typeof HelloRequest,
      readonly O: typeof HelloResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

